name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ' 1.25.0'

      - name: Install dependencies
        run: make deps

      - name: Format & Vet code
        run: |
          make fmt
          make vet

      - name: Run tests
        run: make test
